# Site settings
title: Random developers thoughts
email: vuvej@beotel.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://veljkopopovic.github.io" # the base hostname & protocol for your site
twitter_username: veljislav
github_username:  veljkopopovic

# Build settings
markdown: kramdown
